### ISSUE TITLE
Add column type information on a subdataset level

### ISSUE THREAD

**Issue by edwardleardi** [CODAIT/exchange-metadata-converter#4]
This data would be fed to both the DAX API and to our DAX data previews. 

Propose this structure:

```yaml
content:
  - file_name: noaa-weather-data-jfk-airport/jfk_weather.csv
    description: Raw data file
    records: 114546
    size: 30M
    type: CSV
    mime_type: text/csv
    column_types:
      STATION: str
      STATION_NAME: str
      ELEVATION: float
      LATITUDE: float
      ...
```
