### ISSUE TITLE
Determine how to handle subdataset level type fields

### ISSUE THREAD

**Issue by edwardleardi** [CODAIT/exchange-metadata-converter#6]
Information on how to locate all the files belonging to a certain subdataset is important for the DAX API and how it handles loading in subdatasets. Note, this is different from a subdataset's format, which is simply the file format of the subdataset.

Examples of subdataset types:
* a simple file = it's path name (e.g. txt, csv)
* a directory (e.g. a directory of image files, a directory of subdirectories)
* a list of files (e.g. a txt with paths to all files in the validation set)
* a regex (e.g. all train files have `train_` appended at the start of the filename)

We need to determine what subdataset types there are and how to include this information. The current proposal is this:

Simple file:
```yaml
  - file_name: noaa-weather-data-jfk-airport/jfk_weather.csv
    ...
    format: CSV  # rename from type to format
    ...
    type: path_name
       value: noaa-weather-data-jfk-airport/jfk_weather.csv
```

Regex:
```yaml
  - file_name: publaynet/train
    ...
    type: regex  
      value: "train/*"
```

List of files:
```yaml
  - file_name: tfsc/train_list.txt
    ...
    type: list_of_files  
      value: tfsc/train_list.txt
```

There's probably a better way of structuring this that avoids the `file_name` being the same as the `value` field in some cases,  but it's a start.
